export const homeData = [
    {
      id: 1,
      name: "Upcoming Events",
      time: "20-Jan-2024",
      desc: "Sand and dust storms (SDS), also known as sirocco, haboob, yellow dust, white storms, and the harmattan, are a natural phenomenon linked with land and water management and climate change.",
      starring: "Karen Gilchrist, James Earl Jones",
      genres: "Action",
      tags: "Action, Adventures, Horror",
      cover: "https://img.freepik.com/premium-photo/illustration-girl-boy-dancing-rave-party-beach_917664-32049.jpg?size=626&ext=jpg&ga=GA1.1.386372595.1698537600&semt=ais",
      video: "../video/video1.mp4",
      date: "20-Jan-1997",
    },
    {
      id: 2,
      name: "Trending Dance",
      rating: 4.6,
      time: "10-JUL-2021",
      desc: "The island, like its inhabitants, is wholly fictional. Kong's island home in the Pacific makes its first appearance, along with Kong himself, in the 1933 film King Kong. ",
      starring: "Brenda Chapman, Jeff Nathanson",
      genres: "Adventures",
      tags: "Adventures,Animation,Family",
      cover: "https://getwallpapers.com/wallpaper/full/9/9/b/609924.jpg",
      video: "../video/video2.mp4",
      date: "10-JUL-2021",
    },
    {
      id: 3,
      name: "Dance",
      rating: 4.8,
      time: "10-JUL-2021",
      desc: "Piracy is an act of robbery or criminal violence by ship or boat-borne attackers upon another ship or a coastal area, typically with the goal of stealing cargo and other valuable items or properties. ",
      starring: "James Chinlund, Jeff Nathanson",
      genres: "Adventures",
      tags: "Adventures,Action ",
      cover: "https://png.pngtree.com/background/20230319/original/pngtree-dancing-solo-colorful-background-picture-image_2151086.jpg",
      video: "../video/video3.mp4",
      date: "20-FEB-2010",
    },
    {
      id: 4,
      name: "Sand Dust",
      rating: 4.9,
      time: "10-JUL-2021",
      desc: "Sand and dust storms (SDS), also known as sirocco, haboob, yellow dust, white storms, and the harmattan, are a natural phenomenon linked with land and water management and climate change.",
      starring: "Karen Gilchrist, James Earl Jones",
      genres: "Action",
      tags: "Action, Adventures, Horror",
      cover: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDHLoHLB3DTQPLSZc1vqg4VbGgURdqa4aUS-0ZYyZbs8xG-6Qa1E_0CX2p_olZRWRI3wA&usqp=CAU",
      video: "../video/video4.mp4",
      date: "12-Aug-2015",
    },
  ]
  export const upcome = [
    {
      id: 1,
      cover: "https://i.pinimg.com/736x/1b/b1/dd/1bb1ddf30b68bbf52ca3754040a614b3.jpg",
      name: "My Dream Song",
      time: "09-Feb-2023",
    },
    {
      id: 2,
      cover: "https://c8.alamy.com/comp/2G73TBA/talent-show-singing-contest-dance-competition-magicians-performance-acrobats-onstage-judging-panel-isometric-infographic-flowchart-vector-illustration-2G73TBA.jpg",
      name: "Shadowed",
      time: "09-Feb-2023",
    },
    {
      id: 3,
      cover: "https://wallpapercave.com/wp/Um6ZIKA.jpg",
      name: "Another Danger",
      time: "09-Feb-2023",
    },
    {
      id: 4,
      cover: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSaDARX3F0WWLxlPpHy75CLPrZVBSGnCudj2A&usqp=CAU",
      name: "One Man Army",
      time: "09-Feb-2023",
    },
    {
      id: 5,
      cover: "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a7ceb559799265.5a2fdf2337128.jpg",
      name: "Jumbo Queen",
      time: "09-Feb-2023",
    },
  ]
  export const latest = [
    {
      id: 1,
      cover: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTOrfLPk8t-mMGPEF9JA6QbbqmDTj-rC9hvg&usqp=CAU",
      name: "King of Jungle",
      time: "09-Feb-2023",
    },
    {
      id: 2,
      cover: "https://us.123rf.com/450wm/ydhimas99/ydhimas992304/ydhimas99230400011/203363778-danza-stile-moderno-breakdance-sfondo-multicolore.jpg?ver=6",
      name: "The illusion",
      time: "09-Feb-2023",
    },
    {
      id: 3,
      cover: "https://i.pinimg.com/236x/b7/d8/50/b7d85071c47fa8dae4e0c353a82eba5e.jpg",
      name: "Latest Shows",
      time: "09-Feb-2023",
    },
    {
      id: 4,
      cover: "https://previews.123rf.com/images/pikepicture/pikepicture2003/pikepicture200301221/142061486-karaoke-poster-club-background-mic-design-karaoke-disco-banner-voice-equipment-sing-song-dance-event.jpg",
      name: "Latest two",
      time: "09-Feb-2024",
    },
    {
      id: 5,
      cover: "https://i.pinimg.com/originals/6a/46/21/6a4621e16ee811bc5ff2e3cd8b046956.jpg",
      name: "Latest Three",
      time: "09-Feb-2024",
    },
  ]
  
  export const trending = [
    {
      id: 1,
      name: "The Dinosaur",
      rating: 4.7,
      time: "09-Feb-2024",
      starring: "Brenda Chapman, Jeff Nathanson",
      genres: "Action",
      tags: "Action, Adventures, Horror",
      cover: "https://png.pngtree.com/background/20230401/original/pngtree-dance-passion-dance-summer-party-picture-image_2248960.jpg",
      date: "20-Jan-1997",
    },
    {
      id: 2,
      name: "The Great Emperor",
      rating: 4.6,
      time: "09-Feb-2024",
      desc: "The island, like its inhabitants, is wholly fictional. Kong's island home in the Pacific makes its first appearance, along with Kong himself, in the 1933 film King Kong. ",
      starring: "Brenda Chapman, Jeff Nathanson",
      genres: "Adventures",
      tags: "Adventures,Animation,Family",
      cover: "https://c4.wallpaperflare.com/wallpaper/349/374/432/michael-jackson-suit-hat-dance-colors-michael-jackson-concert-poster-wallpaper-preview.jpg",
      date: "10-JUL-2021",
    },
    {
      id: 3,
      name: "Jumbo Queen",
      rating: 4.8,
      time: "09-Feb-2024",
      desc: "Piracy is an act of robbery or criminal violence by ship or boat-borne attackers upon another ship or a coastal area, typically with the goal of stealing cargo and other valuable items or properties. ",
      starring: "James Chinlund, Jeff Nathanson",
      genres: "Adventures",
      tags: "Adventures,Action ",
      cover: "https://thumbs.dreamstime.com/b/karaoke-party-show-poster-set-music-night-club-festival-drawing-art-prints-man-sing-song-mic-musical-event-artwork-placard-283675649.jpg",
      date: "20-FEB-2010",
    },
  ]
  export const recommended = [
    {
      id: 4,
      cover: "https://i.ytimg.com/vi/uSjrJFrUm_k/maxresdefault.jpg",
      name: "One Man Army",
      time: "09-Feb-2024",
    },
    {
      id: 5,
      cover: "https://akamaividz2.zee5.com/image/upload/w_1170,h_658,c_scale,f_webp,q_auto:eco/resources/0-6-4z5238217/list/1170x658withlogo7b9d6e35474a4664b17f96ec02fb9026.jpg",
      name: "Jumbo Queen",
      time: "09-Feb-2024",
    },
    {
      id: 1,
      cover: "https://image-resizer-cloud-api.akamaized.net/image/AF217DE0-9BC0-423A-8B9E-0C056DFEDCA5/0-16x9.jpg?width=1920&updatedTime=2023-04-25T01:54:12Z&dt=Web",
      name: "My office Boss",
      time: "09-Feb-2024",
    },
    {
      id: 2,
      cover: "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/dance-competition-flyer-design-template-a2c844edb85690ef4feb04a28e8022dc_screen.jpg?ts=1561530228",
      name: "Shadowe",
      time: "09-Feb-2024",
    },
    {
      id: 3,
      cover: "https://cdn.yehaindia.com/wp-content/uploads/2020/05/Indian-Classical-Musicains.jpg",
      name: "Another Danger",
      time: "09-Feb-2024",
    },
  ]
  